### ISSUE TITLE
NppFTP popup directory window sometimes is at invisible location.

### ISSUE THREAD

**Issue by sc1478** [ashkulz/NppFTP#100]
I work on a laptop that I bring from home to office sometimes working in each place.  In each place there are dual-monitor configurations, that are different from each other.  In one, the extra monitor sits to the left of the laptop, in the other the extra monitor sits to the right.  OS is Windows 7 - 64 bit.

When switching between these two environments, NppFTP sometimes becomes confused about where this window is.  I cannot find it on either screen, and clicking the "Show FTP Window" or "Focus FTP Window" menu items (by the way, what is the purpose of Focus FTP Window and how does it differ from Show FTP Window?) does nothing that I can see.  Evidently this popup's location is stored in some configuration file or the registry - cannot tell which and I have no way of forcing the directory popup window to appear.  When I go back to the other work location, the window appears.

There should be some way to force the popup into visibility or at the very least, please document a procedure for making it appear.  This is very annoying behavior.  I would welcome any workaround.

**Comment by sc1478** [comment]
A workaround is, with Npp not running, to turn of dual monitor display, then start Npp and make NppFTP visible, and then revert to dual monitor.

**Comment by sc1478** [comment]
And now this workaround no longer works!  I can't make nppftp visible no matter what I do!  
Can we get a fix for this!

**Comment by sc1478** [comment]
Can I PLEASE get someone to take a look at this issue?

I really liked the NppFTP plugin when I could see it, but now I can no longer use it.   Someone, please, give me an idea how to get around this issue

**Comment by mausolos** [comment]
I also have this problem. Extremely frustrating! Bump!

**Comment by chcg** [comment]
See followup discussion in #134 with workaround, also not suitable for a daily usage.

**Comment by quetal2** [comment]
Where is this config file to be found?

**Comment by chcg** [comment]
@quetal2  Normally at %AppData%\Notepad++\config.xml for installed versions
