### ISSUE TITLE
Win 32 Error when opening npp

### ISSUE THREAD

**Issue by Nicon4454** [ashkulz/NppFTP#106]
getting an error when opening npp with the nppFTP installed
http://prntscr.com/cqqjd9 <== this is the error i get

http://prntscr.com/cqqkac <== this is the ver of npp i am running

**Comment by vlakoff** [comment]
This is because 64-bit Notepad++ cannot use 32-bit plugins.

**Comment by ashkulz** [comment]
This has been fixed with the latest release [`v0.26.7`](https://github.com/ashkulz/NppFTP/releases/tag/v0.26.7) which includes a 64-bit build.
