### ISSUE TITLE
Notepad++ 64bit compatability

### ISSUE THREAD

**Issue by imcdona** [ashkulz/NppFTP#108]
Notepad++ now provides a 64bit build as of [version 7 released 09/22/2016.](https://notepad-plus-plus.org/news/notepad-7-released.html)

Please consider providing a 64bit build of NppFTP.

Thanks

**Comment by imcdona** [comment]
The owner of this plug in is looking for someone to take over development going forward. If you're interested please let him know.

His comments can be found here:

https://github.com/ashkulz/NppFTP/issues/104

**Comment by ashkulz** [comment]
This has been implemented with the latest release [`v0.26.7`](https://github.com/ashkulz/NppFTP/releases/tag/v0.26.7). Still looking out for a new maintainer, though...
