### ISSUE TITLE
Please Compile

### ISSUE THREAD

**Issue by mean-cj** [ashkulz/NppFTP#11]
Thank you very very much for your update. 

A great feature would be to change chmod for files and directories.

I add feature of chmod
https://github.com/mean-cj/NppFTP/commits/master

please compile test , or please tell me how to compile on linux

**Comment by mean-cj** [comment]
I think compile on windows better. ^^

**Comment by ashkulz** [comment]
Use the instructions in `BUILDING` to see how to compile it on Windows. For Linux, you can compile it by running on Debian/Ubuntu: `sudo apt-get install mingw-w64` and just running `make` -- please note that you'll have to install Notepad++ and run it in WINE, which I haven't really tested as such. Once you finish your changes, please squash them into logical commits and submit a PR.

**Comment by mean-cj** [comment]
Thanks for your suggenstion,

file FTPWindows.cpp

i want to create new method please tell me how to get int value
const TCHAR * newMode = id.GetValue();

I can't cast string to int
```c
const TCHAR * newMode = id.GetValue();
const int newMode_cp = (int)newMode ;
```

```c
int FTPWindow::Chmod(FileObject * fo) {
	InputDialog id;

	//int res = id.Create(m_hwnd, TEXT("Change Permission"), TEXT("Please enter the number of permission:"), fo->GetPermssion());
	int res = id.Create(m_hwnd, TEXT("Change Permission"), TEXT("Please enter the number of permission:"), TEXT("Enter Number"));
	if (res != 1)
		return 0;


	const TCHAR * newMode = id.GetValue();
	 int newMode_CP = (int)SU::TCharToCP(newMode, CP_ACP);


	res = m_ftpSession->Chmod(fo->GetPath(), newMode_CP);
	if (res == -1)
		return -1;

	m_ftpSession->GetDirectory(fo->GetParent()->GetPath());

	return 0;
}
```

**Comment by tbeu** [comment]
@mean-cj you may use ```strtol``` after conversion from TCHAR* to char*.
```c++
const TCHAR * newMode = id.GetValue();
char* newMode_ACP = SU::TCharToCP(newMode, CP_ACP);
char* endptr;
int newMode_cp = (int)strtol(newMode_ACP, &endptr, 10);
if (*endptr != 0) {
   // do error handling
}
```
