### ISSUE TITLE
release v0.26.8

### ISSUE THREAD

**Issue by ashkulz** [ashkulz/NppFTP#126]
It would be good to bump the version and release `0.26.8` with the security updates for zlib, OpenSSL and libssh.

Also, would be good if the latest version were pushed to Plugin Manager -- do you have an account at the [plugins repository](https://npppm.bruderste.in)? Let's co-ordinate so that you can update it over there as well.

**Comment by chcg** [comment]
Yes. I will check out how to merge.

Not yet registered. I will request a login.

**Comment by ashkulz** [comment]
Did you get a login yet? I had one previously, but they've migrated to a new location.

**Comment by chcg** [comment]
Unfortunately I got no mail reply after registering. I guess Dave Brotherstone is really checking the requests manually and doing it just from time to time.

**Comment by chcg** [comment]
I have access now. There a some issues with the email behind the server therefore the email is not send to a new user and also dave is not informed about a new request.

What is the status of your account now?

**Comment by ashkulz** [comment]
No idea, really. There's no reset password option... might make sense for you to publish a new version there.

**Comment by chcg** [comment]
Have a look at https://github.com/ashkulz/NppFTP/releases/tag/v0.26.8 if this is ok.

**Comment by ashkulz** [comment]
Looks good :+1:

**Comment by chcg** [comment]
registered this version at plugin manager, could be tested with the settings to use the development plugin list
