### ISSUE TITLE
When copying profiles some settings are not copied

### ISSUE THREAD

**Issue by Dragorn421** [ashkulz/NppFTP#127]
Hello,

When you go in Profile settings and then hit "Copy" to make a copy of a profile all goes well, except that some options seem to get reset to default for the new one. I didn't do extended testing, but that is a problem for at least the "Ask for password" (in Connection) and "Ask every time"(for passphrase in Authentication). On the original profile I have the first one unchecked and the second one checked, on the copy it's the opposite (back to default I guess).

Thanks for the tool too, it's great :D

**Comment by chcg** [comment]
Fixed with release https://github.com/ashkulz/NppFTP/releases/tag/v0.26.8
