### ISSUE TITLE
Can't drag/drop to upload files after update

### ISSUE THREAD

**Issue by BartHumphries** [ashkulz/NppFTP#13]
On Windows 10, I used to be able to open a folder in another window over/next to Notepad++, then I could drag the file over to the NppFTP window to any folder shown there, and the file would be uploaded.  The recent update breaks that.

**Comment by ashkulz** [comment]
What is the version you are using right now, and what was the previous version?

**Comment by BartHumphries** [comment]
The current version is 0.26.1 -- I don't know what the previous version
was, but I was using it all last semester, so whatever version came
installed with Notepad++ then.  At the same time that I upgraded to the
newest version of the NppFTP plugin, I also upgraded the Notepad++ Plugin
Manager, although I don't see how that would make a difference.  The notes
for the NppFTP plugin in Notepad++ say:
NppFTP: a plugin that allows FTP, FTPS, FTPES and SFTP communications. Very
useful for web development.
Author: harrybharry, ashish_kulz
Homepage: http://sourceforge.net/projects/nppftp/
Latest update: * zlib updated from 1.2.4 to 1.2.8 (precompiled)
* OpenSSL updated from 0.9.8n to 1.0.1k (precompiled)
* libssh updated from 0.4.4 to 0.6.4 (precompiled)
* TinyXML updated from 2.6.1 to 2.6.2
So the problem could potentially lie with any of those

Previously, when I opened a folder on my Windows 10 PC (tech preview) and
dragged a file from that regular folder over to a folder shown in the
NppFTP plugin, it would upload the file.  Now, when I mouse the document
over the plugin window, it shows a "no" graphic, a circle with a diagonal
slash.

It could also be related to a Windows update, I suppose -- are you still
able to drag/drop files and see them uploaded with the latest version?

Bart Humphries
bart.humphries@gmail.com
(909)529-BART(2278)

**Comment by ashkulz** [comment]
OK, so you were probably using an older version. Can you go to the [SourceForge downloads](http://sourceforge.net/projects/nppftp/files) and see which is the last version where this works?

**Comment by tbeu** [comment]
Cannot reproduce on Win7 with NppFTP_0.26.2.zip, NppFTP_0.26.1.zip, NppFTP_0.26.zip, NppFTP_0.25.zip.

**Comment by ashkulz** [comment]
So maybe a breakage due to Windows 10?

**Comment by ashkulz** [comment]
@BartHumphries: please reopen the issue when you can provide more details.

**Comment by ismael-miguel** [comment]
I've seen this happen both on Windows and Linux (Wine).

If Notepad++ is running as Administrator (default on Wine), you can't drop files on NppFTP.

I know this is a 4-years-old issue, but, I noticed this 2-3 years ago and has been consistent since then.
