### ISSUE TITLE
release v0.26.9

### ISSUE THREAD

**Issue by ashkulz** [ashkulz/NppFTP#136]
- [x] add @chcg to maintainers list in "About" dialog and website
- [ ] port remaining features in hand-written Makefile and remove it
- [x] update `BUILDING.md` with instructions for both cross-compilation and native MSVC build
- [x] publish to Plugins Manager
- [x] fix for #122

**Comment by ashkulz** [comment]
BTW, I've enabled AppVeyor on this repository now.

**Comment by chcg** [comment]
ok. merge fix for #122

**Comment by chcg** [comment]
release done.

Open points:
- port remaining features in hand-written Makefile and remove it
- think also BUILDING.md needs some further adaptions and correction after the porting is done
