### ISSUE TITLE
v0.26.8 -> User cannot log in.

### ISSUE THREAD

**Issue by hallucin** [ashkulz/NppFTP#138]
Hi, IDK why it wont work but with total commander it works but in this version it wont. Just to report...

**Comment by ashkulz** [comment]
Details of error?

**Comment by hallucin** [comment]
-> TYPE I  
Connecting
-> Quit  
220 Microsoft FTP Service
-> USER TEST
331 Password required for andeyanc.
-> PASS *HIDDEN*
530 User cannot log in.
Unable to connect
Disconnected

Is it related to #122 ?

**Comment by chcg** [comment]
@hallucin Which connection type have you set? FTP, FTPS, FTPES, SFTP? #122 might just hit you with FTPS, FTPES. Is it a public FTP server with an anonymous login?

**Comment by hallucin** [comment]
It's FTP. No it isn't public FTP with anonymous login. Is there some option to show debug so I can copy paste info?

**Comment by chcg** [comment]
@hallucin 

just release fix for TLS v1.2 support as version https://github.com/ashkulz/NppFTP/releases/tag/v0.26.9. It is available also from PluginManager with Setting ->use development plugin list and in ~2 weeks as regular update.
Maybe you could give it a try also I think this is a unrelated issue. 
Does the password contain non ASCII characters? There are some issues open on that.

**Comment by hallucin** [comment]
Thank you guys for response and willing to help me. I changed password and now it works.
Keep this project up please!
~Dejan
