### ISSUE TITLE
release v0.27.0

### ISSUE THREAD

**Issue by chcg** [ashkulz/NppFTP#139]
- [ ] port remaining features in hand-written Makefile and remove it
- [ ] think also BUILDING.md needs some further adaptions and correction after the porting is done
- [ ] probably major issue in porting is currently the dll name starting with lib with the mingw build

**Comment by ashkulz** [comment]
It's time to bump up the minor revision number, since there have been a lot of changes and a new maintainer :+1:

**Comment by ashkulz** [comment]
The issues #52, #75, #135 and #144 have also been fixed in this release.

**Comment by chcg** [comment]
#155 update libssh to version 0.7.5

**Comment by chcg** [comment]
See https://github.com/ashkulz/NppFTP/releases/tag/v0.27.0

**Comment by ashkulz** [comment]
None of the points got released, maybe another day :wink:

**Comment by chcg** [comment]
Focused on bugs more than build infrastructure changes for this release.
