### ISSUE TITLE
Hello Please help.

### ISSUE THREAD

**Issue by mean-cj** [ashkulz/NppFTP#14]
Hello Please help, how to cast variable type

const char * mode ===>  mode_t mode
because sftp_chmod request variable type is int or mode_t

Now normal ftp can be change permission but sftp can't because the permission number is incorrect.

# FTPClientWrapperSSH.cpp
```c
int FTPClientWrapperSSH::ChmodFile(const char * path, const char * mode) {

	//int cpmode = atoi(mode) ;
	//mode_t perm = strtoul(mode, 0, 9);
	//OutMsg("FTPClientWrapperSSH::ChmodFile %s == %s =", strtoul(mode, 0, 9), mode );

	int retcode = sftp_chmod(m_sftpsession, path, mode);

	return OnReturn((retcode == 0)?0:-1);
}
```
# sftp.h
```c
LIBSSH_API int sftp_chmod(sftp_session sftp, const char *file, mode_t mode);
```

## Test 
sftp_chmod(m_sftpsession, path, 0755); //work
sftp_chmod(m_sftpsession, path,  atoi(mode)); //doesn't work
sftp_chmod(m_sftpsession, path,  (int)mode); //doesn't work
sftp_chmod(m_sftpsession, path,  strtoul(mode, 0, 9));  //doesn't work

mode_t perm = strtoul(mode, 0, 9);
sftp_chmod(m_sftpsession, path, perm);  //doesn't work

Thanks

**Comment by mean-cj** [comment]
ok fixed

	mode_t perm = (mode_t) strtoul(mode, 0, 8);
	int retcode = sftp_chmod(m_sftpsession, path, perm );

**Comment by ashkulz** [comment]
Please don't create issues for help like this, use StackOverflow or ask via email.
