### ISSUE TITLE
Failure retrieving contents of directory /

### ISSUE THREAD

**Issue by KAKASHI0** [ashkulz/NppFTP#145]
Connected
-> CWD /  
250 Directory successfully changed.
-> PASV  
227 Entering Passive Mode (10,8,15,114,238,94).
-> LIST  
Failure retrieving contents of directory /

**Comment by yanislavtankov** [comment]
I have similar issue while connecting to some hosting providers.

**Comment by chcg** [comment]
Maybe related to #120

**Comment by chcg** [comment]
@KAKASHI0 @yanislavtankov Could you please contribute to #120 for further tracking this issue.

Which kind of FTP connection do you use? FTP, FTPS, FTPES, SFTP?

**Comment by fana11** [comment]
got it OK with FTP option checked.
