### ISSUE TITLE
how to install nappftp?

### ISSUE THREAD

**Issue by bobbygibson** [ashkulz/NppFTP#151]
### Description of the Issue
I would like to connect notepad++ via ftp to my web server so I can upload things directly. I understand I need to use NppFTP.

All the installation instructions say to go to Plugins > Show NppFTP... but it isnt there for me... I'm on a windows 7 machine and just installed the 64bit version of Notepad++ via the installer. The only options I have under "Plugins" is Converter and MIME Tools.

I have found where I can download NppFTP from but it says to use the "plugin manager" under the "plugin menu" which again isnt there....

Thanks,

**Comment by chcg** [comment]
Pluginmanager is not available yet as functional 64bit version see https://github.com/bruderstein/nppPluginManager/issues/7.

So there is just the option of manual installation of NppFTP. Download https://github.com/ashkulz/NppFTP/releases/download/v0.26.9/NppFTP-x64.zip and copy the dll from bin to the plugin dir inside of your N++ installation.

**Comment by joancatala** [comment]
I installed an old version (7.2) and it worked.

You have the link in the official website, just change the version. Is this URL: https://notepad-plus-plus.org/download/v7.2.html

Worked like a charm.

**Comment by chcg** [comment]
In the meantime N++ 7.6 is available with Plugin Admin built-in, see https://notepad-plus-plus.org/news/notepad-7.6-released.html. In that plugin list NppFtp is already available.
