### ISSUE TITLE
Bad directory/file sorting order

### ISSUE THREAD

**Issue by rsakakr** [ashkulz/NppFTP#157]
### Description of the Issue

There is a bug in the FileObject::CompareFO() method:

```
bool FileObject::CompareFO(const FileObject * fo1, const FileObject * fo2) {
	int res = 0;
	if (fo1->isDir() != fo2->isDir()) {
		res = fo1->isDir()?false:true;
	} else {
		res = lstrcmpiA(fo1->GetPath(), fo2->GetPath());
	}
	return (res < 0);
}
```

Proper expression for **res** (which is an _int_, not _bool_) for the _directory vs file_ comparison case shall be:

`		res = fo1->isDir() ? -1 : +1;
`

Strangely enough, the bad sorting order doesn't appear in latest official NppFTP deliveries, only when using source code compiled under MS Visual Studio.

### Steps to Reproduce the Issue

1. Clone http://github.com/ashkulz/NppFTP, use latest commit, after v0.26.9, master branch
2. Configure to using MS Visual Studio Community 2015: `cmake -G "Visual Studio 14 2015"`
3. Rebuild as Release
4. Copy NppFTP.dll to Notepad++ plugin subdirectory
5. Open Notepad++, start NppFTP session

### Expected Behavior

That directory and file names are sorted alphabetically.

### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/28783342/26239477/73a204c0-3c7d-11e7-8feb-39c426392916.png)
Not properly sorted.

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

NppFTP version:  0.26.9 Unicode
Using SFTP, private keyfile

**Comment by zetwin** [comment]
+

**Comment by rsakakr** [comment]
Same issue reported in #160, #180, #183.
Finally fixed in https://github.com/ashkulz/NppFTP/releases/tag/v0.27.1

**Comment by chcg** [comment]
@rsakakr Unfortunately I first saw and analysed #160, but not this one with the proper fix already contained. Thanks anyway.

**Comment by rsakakr** [comment]
@chcg You couldn't see my past comments/contributions because my account has been unexpectedly "flagged" by the stubborn security bot when I was on vacation. Good that we found the same solution!
