### ISSUE TITLE
unknown exception when starting npp; cannot start nppftp

### ISSUE THREAD

**Issue by mfinky** [ashkulz/NppFTP#16]
Hi.

First of all: excellent plugin.  Love it and use it all the time to develop web sites.

Description of current Incident:
I am using 
* Windows 8.1, all Windows updates installed. 
* Notepad++ "je suis charlie" edition (no update is available).
* Plugin manager 1.3.5.0

I was able to use nppftp a few days ago with no issues at all.
Today (15-Feb-2015) when i launched notepad++ with "run as administrator" i received an error message "Unknown Exception".
Clicked OK, and the program continued.  Apparently functional.
When i tried to open nppftp i did not see the usual window opening.  no errors or messages at that point but nppftp was not starting.

i noticed there was a new version of nppftp so i updated it.  => Same issue.

I uninstalled the nppftp and npp started without any error messages.
I tried launching npp not 'as administrator', but that did not change this behavior.

Googled a little to see if others had reported anything similar but could not find anything.

Please provide instructions on what to do next.?

Thanks,
Marcelo Finkielsztein.

**Comment by mfinky** [comment]
I found i was using nppftp 0.26.1, while the latest version on sourceforge was 0.26.2.
I downloaded this latest version, replaced the .dll and now things work as expected.

Note please that the npp plugin manager does not take care of installing this (0.26.2) version.  not sure why.  i realize this might be something for the plugin-manager developers to solve.

Cheers.
Marcelo Finkielsztien

**Comment by ashkulz** [comment]
I've updated the PluginManager admin area, but it isn't deployed automatically -- the PluginManager devs batch the updates so you can have a delay sometimes.

**Comment by mfinky** [comment]
Thank you ashkulz,  i appreciate it.
It is good to know that these delays can happen.  
In any case, as said before, after updating manually, things work as expected.
Cheers,
Marcelo
