### ISSUE TITLE
Can't open two files with the same name in the same directory but different uppercase/lowercase combinations

### ISSUE THREAD

**Issue by spencerbug** [ashkulz/NppFTP#161]
### Description of the Issue
NppFTP cannot open two files with the same name 

### Steps to Reproduce the Issue

1.  SFTP to a linux machine 
2. Create a folder "myfolder"
2. In this "myfolder", create a file called "myfile"
3. Create another file called "MYFILE", in the same directory, note all caps
4. Create another file called "MyFile", in the same directory,  note the caps

### Expected Behavior

NppFTP can open all three files 

### Actual Behavior

NppFTP can only open one of these files at a time.

### Debug Information

Notepad++ running in Windows 7 64 bit
SFTPing to Ubuntu 12.04
NppFTP version: 0.26.9 Unicode
SFTP
password authentication

**Comment by chcg** [comment]
Known issue, see #3
