### ISSUE TITLE
unable to download nppftp 0.70

### ISSUE THREAD

**Issue by schnaggi** [ashkulz/NppFTP#162]
Used https://github.com/ashkulz/NppFTP/releases/tag/v0.27.0 and 32bit and 64bit version. Both version "replied" with an xml file instead of an zip

first lines are
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

I don't know if this is github issue or not.

**Comment by ashkulz** [comment]
Do you mean via Plugin Manager? If so, @chcg has access to it. The links work for me right now.

**Comment by schnaggi** [comment]
Firefox 53.0.3 with NoScript does not work
Tested with Edge now, working. I set it to resolved but it is strange
