### ISSUE TITLE
Access denied key auth

### ISSUE THREAD

**Issue by Tampa** [ashkulz/NppFTP#163]
Trying to connect to root user using key auth. Key is in openssh format with .ppk extension, generated as RSA with 2048 bits. 

NppFTP reports:

[SFTP] Error during authentication: Access denied. Authentication that can continue: publickey
Unable to connect

Server auth.log

Received disconnect from xxx.xxx.xx.xxx port 34184:11: Bye Bye [preauth]
Disconnected from xxx.xxx.xx.xxx port 34184 [preauth]

I tried the stackoverflow solutions. Saved as .pem and in openssh format. Same error still.
I'm not sure how to debug this any further, where should I look for information as to why it is failing to connect?

**Comment by chcg** [comment]
@Tampa You may want to test current release https://github.com/ashkulz/NppFTP/releases/tag/v0.28.0 which contains updated libssh version 0.8.6 with support for additional algorithms.

**Comment by chcg** [comment]
Please reopen, if still relevant with current version 0.29.4.

**Comment by Tampa** [comment]
I tried it again and it appears to be working now, even saved the passphrase and all. Not sure if it supports all key types but the non-openssh one worked fine. Thanks for fixing!
