### ISSUE TITLE
SFTP connection suddenly doesn't work. Works in other applications.

### ISSUE THREAD

**Issue by Menelo** [ashkulz/NppFTP#164]
As of today I cannot connect via SFTP, it keeps popping error message: 
[SFTP] Connection failed : kex error : no match for method kex algos: server [diffie-hellman-group-exchange-sha256], client [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1] 

I've tried connecting with WinSCP, and SFTP worked without issues, so I guess the problem is with NppFTP.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

version of Notepad++: v7.3.3 (32-bit)
type of FTP connection: SFTP
type of authentication: password

**Comment by chcg** [comment]
@Menelo NppFTP uses libssh to support sftp. The supported algorithms are the ones mentioned in the trace:

client [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1]

, see https://www.libssh.org/features/

So there will be no support for diffie-hellman-group-exchange-sha256 without the support from libssh for it. 

See also https://blog.gdssecurity.com/labs/2015/8/3/ssh-weak-diffie-hellman-group-identification-tool.html, where it is stated that this KEX Algorithm is part of RFC 4419.

Maybe you want to add a feature request at https://red.libssh.org/projects/libssh/issues.

**Comment by chcg** [comment]
@Menelo You may want to test current release https://github.com/ashkulz/NppFTP/releases/tag/v0.28.0 which contains updated libssh version 0.8.6 with support for additional algorithms.

**Comment by Ben-Voris** [comment]
Please, would you close this?

**Comment by chcg** [comment]
As there is no response from creator -> closed
