### ISSUE TITLE
Does not support UTF-8 file names

### ISSUE THREAD

**Issue by CHN-MuXin** [ashkulz/NppFTP#166]
NppFTp does not support utf-8 filenames

Double word characters garbled

**Comment by chcg** [comment]
@x0penghui 
- Which kind of FTP connection? Plain, SFTP, FTPS, FTPES?
- Do you have any public ftp server to test\reproduce this? 
- Which version of NppFTP?

**Comment by chcg** [comment]
Duplicate to #55
