### ISSUE TITLE
kex error

### ISSUE THREAD

**Issue by hktang** [ashkulz/NppFTP#167]
### Description

It seems after an NPP upgrade, NppFTP no longer works. I am running it on Windows 7. 

### Debug Information

Here's the console output: 

    Connecting
    [SFTP] Connection failed : kex error : no match for method kex algos: server [diffie-hellman-group-exchange-sha256], client [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1] 
    Unable to connect
    Disconnected

Thanks, everyone in advance for any suggestion/hint/solution...

**Comment by rockachman** [comment]
I've been having the same problem.  I'm trying to see if my hosting service will allow me to add those ciphers listed on the client side for authentication (not sure it's advisable, but I have work to get done!).  Right now they only accept "diffie-hellman-group-exchange-sha256" according to the kex error I'm getting.

**Comment by ashkulz** [comment]
It's not [supported by libssh](https://www.libssh.org/features/), probably because [it's not secure](https://jbeekman.nl/blog/2015/05/ssh-logjam/).

**Comment by chcg** [comment]
Duplicate to #164
