### ISSUE TITLE
Icons too small on 4K screens

### ISSUE THREAD

**Issue by daughtkom** [ashkulz/NppFTP#171]
### Description of the Issue
The icons at the top of the file/folder list are very tiny when viewed on a 4K screen.

### Steps to Reproduce the Issue
1. Use laptop with 4K display 
2. Install NppFTP plugin

### Expected Behavior
Button/icons to be similar in size to the icons used in the main Notepad++ toolbar.

### Actual Behavior
Buttons are very small.

### Debug Information
Notepad++ v7.4.2   (32-bit)
Admin mode : OFF
NppFTP version: 0.26.9

![image](https://user-images.githubusercontent.com/1824392/27767187-10c68090-5ea3-11e7-8128-fe966645f2c0.png)

**Comment by chcg** [comment]
Needs to have some dpi awareness handling in https://github.com/ashkulz/NppFTP/blob/master/src/Windows/Toolbar.cpp, similar to https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/ToolBar/ToolBar.cpp with

{code}
int iconSize = NppParameters::getInstance()->_dpiManager.scaleX(_state == TB_LARGE?32:16);
{code}

, but also named identical NppFTP is not directly comparable with the current N++ version. Maybe based on some old version at time of NppFTP initial commit around 2010.

**Comment by Aaviator** [comment]
Any progress on this?
