### ISSUE TITLE
release zip files not downloadable

### ISSUE THREAD

**Issue by Becker-Asano** [ashkulz/NppFTP#175]
### Description of the Issue
The latest release file for the 64 bit version does not work. Only an xml-file is shown. Maybe a general github problem?

### Steps to Reproduce the Issue
Try here: https://github.com/ashkulz/NppFTP/releases/tag/v0.26.7

### Expected Behavior
zip file download started.

### Actual Behavior
xml file shown.

**Comment by chcg** [comment]
@Becker-Asano Can't reproduce this behaviour. Download was possible without a problem for me. Could you please retry, maybe also the 32bit version or the source. Which browser are you using and what is the content of the xml file?

**Comment by chcg** [comment]
No reaction and no further such issues opened -> close
