### ISSUE TITLE
Files no longer sorted

### ISSUE THREAD

**Issue by nummacway** [ashkulz/NppFTP#180]
### Steps to Reproduce the Issue
Connect

### Expected Behavior
List appears sorted by name.

### Actual Behavior
List appears in random order.
![bild1](https://user-images.githubusercontent.com/24881711/29670639-8f4139ba-88e7-11e7-9bc7-9c9fa4f98495.png)

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : HexEditor.dll mimeTools.dll NppExport.dll NppFTP.dll PluginManager.dll 

This once worked and happens with FTP und SSH.

**Comment by m-overlund** [comment]
see #160

**Comment by chcg** [comment]
Will be fixed with 0.27.1
