### ISSUE TITLE
directory and filelist not ordered

### ISSUE THREAD

**Issue by Bernbacher** [ashkulz/NppFTP#183]
In the last few weeks there are the directories and files sometimes alphabetically unordered, how can I fix this?
![unordered](https://user-images.githubusercontent.com/31402157/29764424-5100ddc0-8bd7-11e7-88ef-5afa3cd1f649.png)

**Comment by chcg** [comment]
Duplicate to #160 and #180. Already fixed with https://github.com/ashkulz/NppFTP/releases/tag/v0.27.1
