### ISSUE TITLE
Remote folders ordering randomly?

### ISSUE THREAD

**Issue by AFlorencia** [ashkulz/NppFTP#185]
Since last update, remote folders are not ordered alphabetically, instead are arranged in some random order, I don't know wich one.
Here's a screenshot: 
![untitled-2](https://user-images.githubusercontent.com/301174/29844774-dc974846-8ce6-11e7-9903-2b254e993a4f.jpg)

**Comment by m-overlund** [comment]
fixed in newest release - see #180 and #160

**Comment by AFlorencia** [comment]
Thank you!
