### ISSUE TITLE
Feature Request - Profile Groups

### ISSUE THREAD

**Issue by tmueller01** [ashkulz/NppFTP#189]
First I would like to say that it is a great program. I work exclusively with Notepad and NppFTP.

It would be good if you could group the profiles into folders or groups like with FileZilla.

Sample profile folder 1
+ Profiles 1
+ Profiles 2

Sample profile folder 2
+ Profile 1

Best regards

**Comment by ideefixx** [comment]
I use the extension NppFTP for many years. I have a lot of FTP connections deposited and would very much welcome this extension of functionality.

**Comment by ashkulz** [comment]
This has been released in 0.29.0
