### ISSUE TITLE
unable to use rsa-2048 ssh key with sftp

### ISSUE THREAD

**Issue by superka99** [ashkulz/NppFTP#191]
### Description of the Issue

I am getting following errors
[NppFTP] Everything initialized
Connecting
[SFTP] Host key accepted
[SFTP] Banner: ********************* W A R N I N G *********************    
[SFTP] Invalid private key file or incorrect passphrase
[SFTP] Error during authentication: Access denied. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
Unable to connect
Disconnected
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

I was expecting connection since I use the same ssh key with ssh secure shell software and have no problems connecting..I am wondering if there is a certain type of ssh key that needs to be created for this to function correctly..we are using openssh supporting ssh1 and 2 our keys are ssh2

troubleshooting ideas or tips would be greatly appreciated. 
Thank you

Peter
### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : combine.dll mimeTools.dll NppColumnSort.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by chcg** [comment]
@superka99  see #22 maybe a duplicate

**Comment by superka99** [comment]
thank you very much the issue was that the private key wasn't in the openssh format.once I did that ...everything worked as expected!!
PEter

**Comment by chcg** [comment]
Fine.
