### ISSUE TITLE
Profile Settings not changing

### ISSUE THREAD

**Issue by opeeen** [ashkulz/NppFTP#197]
Profile settings not changing when deleting part of the Username (after reopen Profile Settings window - it has still old value)

**Comment by chcg** [comment]
@opeeen Could you describe a little bit more detailed how to repoduce your issue. Couldn't reproduce it from your description.

Furthermore:
- Which N++ and NppFTP version are you using on which Win OS version and bitness ?

**Comment by opeeen** [comment]
windows 7 64 bit
Notepad++ v7.5.1 (32-bit)
NppFTP vesion : 0.26.3 Unicode

1) Profile settings
2) Add new
3) type Username = admin123
4) Push "Close" button
5) Reopen Profile settings, click on this new profile
6) It will be "admin123" - it's ok
7) Now select "123" part of username and press "Delete" button on keyboard
8) Push "Close" button
5) Reopen Profile settings, click on this new profile - it will be still "admin123"

Another words - i think algorithm not triggers save, when pressing delete (otherwise when pressing backspace or just symbols of letters and numbers)

**Comment by chcg** [comment]
Now I can reproduce it.
 The relavant point in the sequence is point 7 to have a text selection and remove it, because if the text is removed by hiding delete for each character that effect doesn't arise.

**Comment by chcg** [comment]
Fix commited with https://github.com/ashkulz/NppFTP/commit/7521f2f1b587f6a1fd9a03027394f1149adce0bf

**Comment by chcg** [comment]
Release with https://github.com/ashkulz/NppFTP/releases/tag/v0.27.4
