### ISSUE TITLE
New Features on My Fork - Need advice on pull request

### ISSUE THREAD

**Issue by mkerost** [ashkulz/NppFTP#20]
This weekend, I made the following changes to NppFTP on my fork:

* Support for NOOP command. This is done through windows timer. I modified SSL client wrapper class so every time it sends an ftp request, it marks the time. When timer checks to see if it should send NOOP command, it only does so if current time compared to time of last sent request is greater than X seconds (defined in profile settings). This should avoid most issues with sending NOOP command if another ftp operation is active.
* In profile, can set interval (seconds) between NOOP requests (0 = disable)
* When saving a file that belongs to a profile that isn't currently active, NppFTP will close the current session and open the profile that belongs to that file, then upload it.
* Modified UTCP library so it parses out permissions info for directory listing and makes this available to NppFTP. Could also get username/group out too and put in tooltip.
* Treeview now supports tooltip when hovering over item. It displays last modified date, file size, and linux permissions.
* Add "debug" checkbox option in settings. By default it is off and console only shows important messages (connecting, uploading file, creating directory, etc). Turn it on and console is verbose with lots of messages and FTP traffic.
* Many consoles messages are now in format "[NppFTP.ClassName] Message". I did this because I compiled on linux but tested on Windows, so needed lots of help debugging issues.

Unfortunately when I compared my branch and master GitHub thinks files are 100% different. So that makes merging tricky. Maybe my editor changed files from UNIX to DOS (editor says it's UTF-8) and I didn't realize it. I will investigate further but have run out of time. If anyone has ideas what to do that will be great.

I also don't know how best to pull requests these features. There's a lot of overlap between them so hard to separate them. In some places I was doing some minor formatting and commenting of code, tried to avoid that because it shows up as changes, but the source code is kind of touch to figure out at times because everything is undocumented.

There also might be issues with string conversions. Haven't used C++ in many years and there were lots of conversions and issues had to figure out... there are probably things that aren't best practices.

**Comment by ashkulz** [comment]
I think the diff is because of the line endings, I just ran the following commands and the diff is more manageable:
```sh
find . -name "*.h" -print0 | xargs -0 unix2dos
find . -name "*.cpp" -print0 | xargs -0 unix2dos
```
You should commit small logical changes which build on top of each other to submit as a PR.

**Comment by mkerost** [comment]
Any of these features you're not interested in? I think I'll have to redo changes from scratch to do proper isolated commits. Save me the time if they won't be used anyway.

Mike

**Comment by ashkulz** [comment]
I'm not really interested in the "debug" flag and the classname in debug messages. Rest all would be great to merge. Hope to see PRs from you soon, and thanks for the contribution!
