### ISSUE TITLE
Connecting to dropbear running on openwrt

### ISSUE THREAD

**Issue by CanadianJeff** [ashkulz/NppFTP#203]
it connects and also displays the banner but fails to list any of the files

```
root@openwrt:~# dropbear -V
Dropbear server v2015.67 https://matt.ucc.asn.au/dropbear/dropbear.html
```

**Comment by chcg** [comment]
Which version of nppFTP are you using? And which protocoll (FTP, FTPS, FTPES, SFTP)? For SFTP see https://wiki.openwrt.org/doc/howto/sftp.server.

**Comment by CanadianJeff** [comment]
installing the sftp server fixed it closing issue
