### ISSUE TITLE
Hostname changes are not stored

### ISSUE THREAD

**Issue by theking2** [ashkulz/NppFTP#213]
Changing a hostname in Profiles is not stored. Change other items are stored.
### Steps to Reproduce the Issue
1. Open a profile
2. Change hostname
3. click Close
4. Reopen the same profile

### Expected Behavior
The new hostname was stored in the profile

### Actual Behavior
The change was ignored

### Debug Information
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppFTP_0.27.0.0.dll PluginManager.dll 
Version 0.27.3.0
Connection type not applicable

See this video: http://youtu.be/zUk9D3ydyR4?hd=1

**Comment by chcg** [comment]
There are two plugins visible in your list:
  NppFTP.dll NppFTP_0.27.0.0.dll 
could this be the problem?

How do you delete the data? Via backspace or Del? In case of del, see #197. Already corrected, just not released yet.

**Comment by chcg** [comment]
Release with https://github.com/ashkulz/NppFTP/releases/tag/v0.27.4
