### ISSUE TITLE
Icon size on 4k displays

### ISSUE THREAD

**Issue by seurrep** [ashkulz/NppFTP#218]
The icons at the top of the nppftp window do not seem to be scaled on 15" 4k displays (in my case a Dell XPS laptop). This leads to tiny buttons that are barely visible and almost unusable

The icons need to be scaled up in size when a high definition screen is in use.

See screenshot:
![image](https://user-images.githubusercontent.com/13554307/37965728-f7a33858-31bd-11e8-8390-ded7dffa0223.png)

**Comment by seurrep** [comment]
Note that the text appears to have been scaled up but not the buttons.

**Comment by Ben-Voris** [comment]
Duplicate of 
https://github.com/ashkulz/NppFTP/issues/171

**Comment by chcg** [comment]
And #171 is already a dup to #84. So please contrib to #84, if you have additional informations/questions
