### ISSUE TITLE
Cannot login with Private Keyfile Authenication

### ISSUE THREAD

**Issue by wattpuppy** [ashkulz/NppFTP#22]
I have a keyfile setup as rsa/1024bit.  I am currently using the same keyfile in WinSCP and Filezilla without a problem.  When I try to login with nppftp i get the following error.

[SFTP] Error during authentication: Access denied. Authentication that can continue: gssapi-keyex,gssapi-with-mic,publickey,password,keyboard-interactive

**Comment by Lotharyx** [comment]
Me too.  Keyfile generated by PuTTYgen, works perfectly with PuTTY and WinSCP.

**Comment by euan-weetch-mccurrach** [comment]
In PuTTYgen, open your key then Conversions -> Export OpenSSH Key

Source: http://stackoverflow.com/questions/8939684/notepad-nppftp-plugin-fails-to-connect-via-sftp

**Comment by matthiku** [comment]
That solved it for me. 
So it seems this is not really a bug, but perhaps an enhancement request to add some info in the GUI of the NppFTP profile configuration to hint about the needed type of private key file.
