### ISSUE TITLE
Disable SFTP cyphers CBC, RC4, 3DES, MD5, and RIPEMD

### ISSUE THREAD

**Issue by oscarjr2001** [ashkulz/NppFTP#222]
Is there a way to disable this cyphers? wpengine removed support for this according to them for security reasons.

Thanks in advance.

**Comment by DavidHaughton47** [comment]
I've hit this problem today too. WPEngine have "removed a few insecure and old key exchange algorithms from the SFTP service" disabling the cyphers above. As Notepad++/ NppFTP is my workhorse for website development, this is a bit of an issue. 

A fix for this asap would be really appreciated.
Thanks :)

**Comment by LOL2011** [comment]
I'm getting the following error when I try to connect to my site hosted on WPEngine:

[SFTP] Connection failed : kex error : no match for method kex algos: server.............

 I assume this is the same problem as what is mentioned above?

**Comment by chcg** [comment]
@oscarjr2001 @DavidHaughton47 See release https://github.com/ashkulz/NppFTP/releases/tag/v0.28.0 with update libssh 0.8.6. Currently supported ciphers are:

> Ciphers: chachae20-poly1305, aes256-ctr, aes192-ctr, aes128-ctr, aes256-cbc, aes192-cbc, aes128-cbc, 3des-cbc, blowfish-cbc

**Comment by chcg** [comment]
As there was no response consider this to be fixed.
