### ISSUE TITLE
Connection error - kex error : no match for method kex algos:

### ISSUE THREAD

**Issue by LOL2011** [ashkulz/NppFTP#223]
Hi,

My notepad and NppFTP setup seem to have stopped working this morning, nothing has changed and all was working fine last night.

I'm getting the following error when I try to connect to my site:

> [SFTP] Connection failed : kex error : no match for method kex algos: server [diffie-hellman-group-exchange-sha256], client [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1] :

**Comment by Ben-Voris** [comment]
This error is caused by a mismatch between the client and server SSH configuration. Search for “match for method kex algos: server”

**Comment by chcg** [comment]
Duplicate to #164 and #167
