### ISSUE TITLE
64 bit Notepad ++ plugin

### ISSUE THREAD

**Issue by Aaront518a** [ashkulz/NppFTP#227]
### Description of the Issue
I'm trying to add the Notepad ++  FTP v 0.26.3 plugin to Notepad ++ v 7.5.8. but the 64 bit version of Notepad ++ won't accept the 32 bit version of NppFTP.  Is there a NppFTP 64 bit version out there?  I can't seem to find one.  Thanks. 

### Steps to Reproduce the Issue

1. Added NppFTP.dll to Notepad++\plugins directory as explained on http://docs.notepad-plus-plus.org/index.php?title=Plugin_Development
2. Opened Notepad ++ but then told the plugin is not compatible
3.

**Comment by MidSpeck** [comment]
Do you mean like the 64-bit versions on the releases page?  0.27.4 is the current latest release.  Both 64-bit and 32-bit downloads listed there.
https://github.com/ashkulz/NppFTP/releases

**Comment by bmccoard** [comment]
This was a pain because I installed the 64-bit Notepad++ and spent 30min trying to get NppFTP to show up in the plugins menu to no avail. After reading this form I uninstalled the 64-bit version and then installed the 32-bit version and now it seems to work.

**Comment by chcg** [comment]
N++ version and plugin version has to match regarding bitness.
Current release is https://github.com/ashkulz/NppFTP/releases/tag/v0.27.6
