### ISSUE TITLE
NppFTP Crashes NPP after connecting to some hosts

### ISSUE THREAD

**Issue by gnppv** [ashkulz/NppFTP#23]
Connecting via NppFTP to a specific type of host (in this case, a router) causes NPP to crash badly on Win 7. Upgraded both NPP (6.7.5) and NppFTP (0.26.2 unicode) to latest. NPP hangs while trying to shutdown and requires force shutdown from Win7. See attached screenshot.
![npp4](https://cloud.githubusercontent.com/assets/11681480/6870104/216b1cf4-d470-11e4-96bb-df5b7d9c24cd.jpg)

**Comment by ElenaLauder** [comment]
Hi,
same issue here. Can I attach here the dump file, for better analyzing?
Thank you & bye,
Elena

**Comment by thejoester** [comment]
I am also having this same issue on multiple computers for the same host. I can connect to other hosts just fine using NppFTP. I can also connect to this host using other FTP clients. 

One thing I noticed is the last command is the Current directory listing. My "Initial remote directory" setting was blank, so I set it to "	/home/www" which works on my other clients and the NppFTP does not crash but gives the error:

550 /home/www: No such file or directory
Failure retrieving contents of directory /home/www

**Comment by chcg** [comment]
@gnppv @ElenaLauder @thejoester Could you please retest this issue with current release 
https://github.com/ashkulz/NppFTP/releases/tag/v0.27.0

which fixes multiple crashes and this one seems to be related to #52

**Comment by thejoester** [comment]
This seemed to resolve the issue for me.


________________________________

**Comment by chcg** [comment]
@thejoester Thanks for the verification.
