### ISSUE TITLE
NppFTP dowloads files from non-ASCII FTP paths, but can not upload (save) them back

### ISSUE THREAD

**Issue by DRSAgile** [ashkulz/NppFTP#230]
I use the latest fully updated NppFTP 0.27.4 Unicode on N++ 7.5.8; and I use the simplest regular FTP connection with all settings by default.

I opened a remote file "ok.html" just fine, edited it, and, as usual, wanted to save it back to a FTP folder, but I failed:

-> STOR /webspace/httpdocs/??????????????????????.????/request/ok.html  
550 /webspace/httpdocs/??????????????????????.????/request/ok.html: No such file or directory

When I opened/downloaded the file the path was converted to letters that look like "Ð" each -- which is obviously incorrect but at least it worked -- but then it was further converted to "?". If the path would stay in the former state then the saving/uploading operation would be still work.

Is there a way to make NppFTP to recognize non-ASCII characters in the paths not only for reading/downloading files but also for saving/uploading them back?

Thank you in advance.

**Comment by chcg** [comment]
Known current limitation, see #55. Currently just the download is supported.
