### ISSUE TITLE
Can not install v0.28 via Plugin Manager in Notepad++ v7.5.9 (64-bit).

### ISSUE THREAD

**Issue by elgholm** [ashkulz/NppFTP#240]
### Description of the Issue
Dialog box:
"It has not been possible to validate the integrity of 'NppFTP.dll' needed to install or update a plugin.  Do you want to copy this file anyway (not recommended)?"

Probably needs to be signed (hash-sum uploaded to Plugin Manager somehow).

### Steps to Reproduce the Issue
1. Try to Install via Plugin Manager.

### Expected Behavior
Installed.

### Actual Behavior
Not installed.
(Since it feels unsafe to give access to my SFTP-passwords to unsigned binaries.)

### Debug Information
None

![nppftp](https://user-images.githubusercontent.com/11699148/51684920-76104a00-1fed-11e9-8458-ba4526509fc7.PNG)

Just wanted to give you a heads up! =)

I can probably install it manually, but it feels safer if signed by author since the plugin actually knows a lot of passwords. ;)

**Comment by chcg** [comment]
@elgholm Thanks for the hint, corrected with https://github.com/bruderstein/npp-plugins-x64/commit/35381f8a670c2949dc0506eae27a3cf0e1ef8a49
