### ISSUE TITLE
Feature Request: Command Line Option To Open notepad++.exe With FTP Connection

### ISSUE THREAD

**Issue by drewwesley** [ashkulz/NppFTP#244]
### Feature Request

It would be helpful to be able to open an instance of Notepad++ with a session already connected to an FTP profile with something like:
C:\Program Files\Notepad++>notepad++.exe -multiInst -openSession <fullpathofsessionfile> -NppFTP <profilename>

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/npp-usermanual/blob/master/command-line.md
that would require a N++ change to forward a command line parameter to a plugin. That is currently not possible.
This request would first need a N++ change. So a https://github.com/notepad-plus-plus/notepad-plus-plus/issues need to be created.
