### ISSUE TITLE
investigate switch to Windows Build Environment on Travis

### ISSUE THREAD

**Issue by ashkulz** [ashkulz/NppFTP#247]
We should investigate switching to [Windows Build Environment](https://docs.travis-ci.com/user/reference/windows/) on TravisCI, so that we've got only one CI tool in place. I recently migrated wkhtmltopdf to use that -- see wkhtmltopdf/wkhtmltopdf@c417e511452cf1b68992de107b6b7f1402ec9e0c

**Comment by chcg** [comment]
Or the other way around as appveyor is supporting linux:
https://www.appveyor.com/docs/linux-images-software/

Additionally there would be the option:
https://azure.microsoft.com/en-us/services/devops/pipelines/

**Comment by ashkulz** [comment]
True, I went with Travis CI because it supports all 3 OSes I need (Windows, macOS and Linux) and there's no restriction on the build times -- AppVeyor has a 1 hour timeout. Azure Pipelines was an option as well but didn't really investigate it.

**Comment by ashkulz** [comment]
@chcg I'm not sure what's going on with the builds -- the Travis CI builds don't update the build status while AppVeyor simply errors out.

**Comment by chcg** [comment]
@ashkulz There is a "random" error with the python urllib download via appveyor. So typically at least one of the 4 build jobs fails. In this case the build result from travis is not retrieved by github, also the build is running and don't show the download issue. Currently I'm not sure if it is a python version issue or an issue with appveyor itself. I already tried to fix it by changing from deprecated urlretrieve() -> urlopen(), but that didn't change the behaviour. Started to happen with
https://ci.appveyor.com/project/ashkulz/nppftp/builds/24874269
and just libssh is affected. Strange.

A different issue I face with the change of travis config from 14.04 -> 16.04. I get linker issues, see:
https://travis-ci.org/ashkulz/NppFTP/jobs/552399212
Do you have an idea how to adapt the config for ubuntu xenial to build?

**Comment by ashkulz** [comment]
I'll look into it in a day or two. Do you wish for us to switch completely to AppVeyor, considering TravisCI is likely [to be on auto-pilot](https://news.ycombinator.com/item?id=19218036) for the near future? The tough part will be to migrate the automatic release creation.

**Comment by ashkulz** [comment]
I fixed the AppVeyor build in #257, will look into the `xenial` upgrade for TravisCI soon.

**Comment by ashkulz** [comment]
The Xenial upgrade is done as part of #258 -- both TravisCI and AppVeyor seem to be reporting now on all builds.

**Comment by ashkulz** [comment]
I think let's just close this ticket for now, and re-look only if there's some pressing need for migration.
