### ISSUE TITLE
Force Ask Passphrase every time

### ISSUE THREAD

**Issue by basti122303** [ashkulz/NppFTP#249]
Hello,
I use Notepad++ with NppFTP in the Company. The users can connect to Server with SFTP and Keyfile. I don't want that users save there Password/ Passphrase on there PC.

In the NppFTP.xml I see That "askPassphrase" is set on every Connection.
It would be a good feature to set a key in the registry to force "AskPassphrase every time".

**Comment by chcg** [comment]
@basti122303 I will accept PRs for that feature, but most probably I won't implement it myself.
Depending on your needs it might be an option to place a company wide npp config file to the N++ installation folder where just admins could modify it.
