### ISSUE TITLE
Profile selection menu is cut off by screen height

### ISSUE THREAD

**Issue by jfreynik** [ashkulz/NppFTP#251]
### Description of the Issue

Profile selection menu runs off of the bottom of the screen when too many profiles exist. I am currently unable to connect to all of my profiles because of this.

### Steps to Reproduce the Issue

1.  Keep adding FTP profiles until the connection menu runs off of the page.

### Expected Behavior

A scrollbar to allow access to the lower profiles or some other manner to connect to all of the profiles.

### Actual Behavior

The menu is cut off at the screen limit.

### Debug Information

![NppFtp-profiles](https://user-images.githubusercontent.com/1813754/57771229-1f379900-76e0-11e9-9b64-78407d4aacf3.png)

**Comment by jfreynik** [comment]
I did just realize that on my larger monitor it actually does display an arrow button at the top and bottom of the screen for reaching the cut off profiles. So that's good enough for me :) - I'll leave the decision up to you whether or not to close the issue (depending if you think there is any value in adding a scrollbar type nav menu).

Thank you!

**Comment by chcg** [comment]
See grouping added with #259.
