### ISSUE TITLE
-> TYPE I   Connecting -> Quit   Unable to connect Disconnected

### ISSUE THREAD

**Issue by tfcroft4** [ashkulz/NppFTP#255]
I have connected to FTP with NNFtp in the past

Today i get this error with all site including the test site
-> TYPE I  
Connecting
-> Quit  
Unable to connect
Disconnected

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : AutoSave.dll ccc.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

version 0.28

FTP

demo password

ftp://test.rebex.net/.

**Comment by drderiv** [comment]
Same exact problem for me.  Only occurs with some FTP servers.  Others work fine.

**Comment by tfcroft4** [comment]
Can any one help with this?
I can connect to FTP servers from this PC using a browser but not from NppFTP
Is there any other log information available that may help the diagnosis?
Thanks
Ted

**Comment by tfcroft4** [comment]
If I use a browser I need to enter ftp://test.rebex.net as the host

In NppFTP the host name is only test.rebex.net

![image](https://user-images.githubusercontent.com/51324348/59552683-1574b000-8f82-11e9-9f08-f9b0fa5b8bbf.png)
