### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by misterunix** [ashkulz/NppFTP#262]
### Description of the Issue

When closing Notepad++ after adding and connecting to a remote server using sftp, 
An exception occurred due to plugin: NppFTP.dll
Exception reason: Access violation

### Steps to Reproduce the Issue

1. Notepad++ 7.7.1 x64 / NppFTP 0.29
2. Add a ssh user / pass
3. Close notepad++ 

### Expected Behavior

Save the config for future use and close cleanly. 

### Actual Behavior

After adding an connection, Exception happens.

### Debug Information

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : D:\NPP\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppFTP.dll 

NppFTP, Copyright 2010-2017
Created by Harry ( harrybharry@users.sourceforge.net )
Maintained by Ashish Kulkarni (kulkarni.ashish@gmail.com)
and Christian Grasser (christian.grasser@web.de)

Press Show FTP Window to get started, and read the documentation (if any) when you get stuck.
For help, info and updates, visit the site by clicking the button below.

Enjoy the comfort of transferring your files from your favorite editor! =)

NppFTP works because of the effort put in the following libraries/projects:
- Ultimate TCP/IP 4.2
- TinyXML 2.6.2
- Silk icons from famfamfam

SFTP

user / pass

local in house CentOS Linux release 7.3.1611

**Comment by chcg** [comment]
Can't reproduce with SFTP test access from https://test.rebex.net/

**Comment by neosixSV** [comment]
same error. it's ok with 0.28.4 version, so downgrade dll

**Comment by chcg** [comment]
Just reproduced the behaviour with latest 0.30.0 version.
Analysis needs further investigations.

**Comment by chcg** [comment]
see https://github.com/ashkulz/NppFTP/releases/tag/v0.30.1
