### ISSUE TITLE
slow connection uploading file via sftp

### ISSUE THREAD

**Issue by fornarini** [ashkulz/NppFTP#277]
i have various computers:
only from 1 of them i am experiencing very very slow uploading of files.
just for example: to save a 20kb file it is using 2 minutes...
a 120kb file it load for 5 minutes...
reinstalling notepad++ didn't solved the problem, also reinstalling only the nppftp module didn't solved the problem.
all pc are in same network (so it is not a server problem), firewall is temporarly disabled.
the bugged pc is the only 1 with windows 10 professional 64 bit, 16gb ram, SSD (it's a gaming pc)
other pc are running windows 7 64 bit, 3gb ram, HDD (very old personal computer)
it is no sense...

edit: running an other ftp client editor (i don't know if i can make the name) it works perfectly. so the problem is happening only with notepad++

**Comment by fornarini** [comment]
edit: running an other ftp client editor (i don't know if i can make the name) it works perfectly. so the problem is happening only with notepad++

**Comment by chcg** [comment]
@fornarini Please test v0.29.5. This should fix the speed up the sftp connection.
