### ISSUE TITLE
Wrong servers Fingerprint

### ISSUE THREAD

**Issue by BugFixNo1** [ashkulz/NppFTP#283]
Sign in to SFTP account a Servers Fingerprint is shown.

### Expected Behavior
The correct and propper Fingerprint must shown. 

MD5 / SHA (ECDSA or RSA as 256 or 2048)

### Actual Behavior
Login procedure shows the wrong Fingerprint... routing over something? Hacked?

### Debug Information

Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\_PortableApps\PortableApps\Notepad++Portable\App\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.973
Plugins : AnalysePlugin.dll AutoSave.dll Autosave2.dll BetterMultiSelection.dll BracketsCheck.dll ColorPicker.dll ComparePlugin.dll DSpellCheck.dll Explorer.dll HTMLTag_unicode.dll ImgTag.dll JSMinNPP.dll LightExplorer.dll MultiClipboard.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppQCP.dll NppQrCode32.dll NppTextFX.dll NppToolBucket.dll PreviewHTML.dll QuickOpenPlugin.dll RunMe.dll SelectQuotedText.dll SpellChecker.dll SurroundSelection.dll Tidy2.dll Translate.dll WindowManager.dll XBrackets.dll zoomdisabler.dll _CustomizeToolbar.dll 

0.29.4 Unicode

SFTP

Passwort

not anonymously accessible

**Comment by chcg** [comment]
You could test against
https://test.rebex.net/

And see the expected values at:
https://sshcheck.com/server/test.rebex.net/

Locally after you accepted a key it could be found at:
<N++ path>\plugins\Config\NppFTP\known_hosts
with data, e.g.:

`test.rebex.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOdXzF+Jx/wvEBun5fxi8FQK30miLZFND0rxkYwNcYlE`

**Comment by rhash** [comment]
NppFTP show hexadecimal representation of SHA1 Fingerprint of ssh key. See [src/FTPClientWrapperSSH.cpp:L651](https://github.com/ashkulz/NppFTP/blob/9cdbc200095937cfa4b318c4e17172153f74157c/src/FTPClientWrapperSSH.cpp#L651): 
```c
rc = ssh_get_publickey_hash(srv_pubkey, SSH_PUBLICKEY_HASH_SHA1, &hash, &hlen);
```

To verify the Fingerprint, obtain SHA1 fingerprints from ssh server:
```sh
ssh-keygen -E sha1 -lf <(ssh-keyscan SSH_SERVER_HOSTNAME 2>/dev/null)
```
If the command above prints fingerprints in the Base64 format, then convert them to Hexadecimal:
```sh
printf %s SHA1_FINGERPRINT_IN_BASE64 | base64 -d | hexdump -C
```
