### ISSUE TITLE
Set permissions on FTP folders

### ISSUE THREAD

**Issue by mbeulens** [ashkulz/NppFTP#286]
### Description of the Issue

In dreamweaver i was able to set the file/directory permissions via the build in FTP client.
I would love to have this feature in NppFTP

### Steps to Reproduce the Issue

1. Create a new directory
2. Set persmission

### Expected Behavior

A contextmenu item and dialog to set permissions

### Debug Information

![persmission_2020-07-11_14-26-58](https://user-images.githubusercontent.com/47374410/87224082-9d460d00-c382-11ea-8d01-3cd1af9ed24a.png)

**Comment by chcg** [comment]
See PR #15 and #199, so I consider this as duplicate to that one.
