### ISSUE TITLE
Passwords containing paragraph § symbol error

### ISSUE THREAD

**Issue by Jan2220** [ashkulz/NppFTP#289]
Hello,
ive noticed a problem with passwords containing paragraph symbols (§). 
The Plugin cant connect to servers with such passwords. Tested with SFTP Protocol
### Steps to Reproduce the Issue
1.  Change your password to something with §
2.  Enter the password in the profile settings of NppFTP
3.  Try to connect

### Expected Behavior
Successful connection to the server

### Actual Behavior
NppFTP wont connect. Output:
[SFTP] Password authentication denied.
[SFTP] Unable to authenticate
Unable to connect

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1016
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll 

NppFTP Version: 0.29.6

Connection Type: SFTP

Authentication Type: Password

Screenshot of the output:
![image](https://user-images.githubusercontent.com/20705433/90342175-7eccd480-e006-11ea-98e8-df317a805661.png)

**Comment by qsek1** [comment]
also psswords containing language special chars like ´ä ö ü´  will not work with nppftp.
Please use UTF-8 charset for passwords.

**Comment by chcg** [comment]
See #21 , currently password input just supports ascii chars.
