### ISSUE TITLE
Left control window disapeared

### ISSUE THREAD

**Issue by jpden0yer** [ashkulz/NppFTP#294]
I've been using NppFTP for a while and like using it. Today The window on the left that allows connecting and shows the remote files completely disappeared! I had notepadd++ open and connected. After doing other stuff I clicked back to notepad++ and the window had completely disappeared. 

I tried the following to get it back: 

- click "show NppFTP window" - This show only the output window at the bottom  

- close and re-open notepad ++

- uninstall and reinstall NppFTP plugin

- log off the remote desktop connection on the server farm and log back in

**Comment by chcg** [comment]
@jpden0yer Which version of N++ and NppFTP  plugin did you use? Were other docking windows like the function list still visible when this problem happened? Happened this just once or could you reproduce it more often?

**Comment by chcg** [comment]
@jpden0yer Is this still an issue? Windows, N++ and NppFTP version would be needed for further analysis. I can't reproduce it with N++ 8.5.2 in Win 10 64 bit with NppFTP v0.29.12.
