### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by superJK92iscool** [ashkulz/NppFTP#301]
When I click "Show NppFTP Window" nothing happens it won't show 

https://user-images.githubusercontent.com/50285310/105646973-9a1af600-5e68-11eb-934a-532a79ea3150.mp4

**Comment by chcg** [comment]
@superJK92iscool Which version of Windows, N++ and NppFTP do you use? 32 or 64bit? With N++ 7.9.2, https://github.com/ashkulz/NppFTP/releases/tag/v0.29.7 on Win10 64bit.
Maybe it is also related to the combination of your installed plugins.

**Comment by superJK92iscool** [comment]
Closing and reopening n++ fixed it
