### ISSUE TITLE
"kex error" since upgrade of SSH daemon

### ISSUE THREAD

**Issue by jaymore** [ashkulz/NppFTP#31]
Since our server have upgraded the OpenSSH daemon, the NPPFTP plugin cant connect any more : 
```
[SFTP] Connection failed : kex error : no match for method mac algo client->server: server [hmac-md5,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512], client [hmac-sha1] 
Unable to connect
```
It seems that NppFtp with LibSSH 0.6.5 is not compatible with the last openssh.

**Comment by ashkulz** [comment]
What is the OpenSSH version and what is the environment it is using?

**Comment by jaymore** [comment]
Hello,

OpenSSH version : 
SSH-2.0-OpenSSH_6.7 PKIX

Env : 
Suse Linux Enterprise Server 11, level 2 3.0.101-0.7.23-xen #1 SMP Tue Aug 19 15:56:19 UTC 2014 (26d8f4e) x86_64 x86_64 x86_64 GNU/Linux

**Comment by Mrten** [comment]
I got a similar complaint from a co-worker (so I don't have the exact message, sorry), our SSH config follows recommendations from [here](https://stribika.github.io/2015/01/04/secure-secure-shell.html).
We have OpenSSH 5.9, relevant piece of sshd config:
```
KexAlgorithms diffie-hellman-group-exchange-sha256
Ciphers aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160
```
@jaymore, can you see something comparable in your /etc/ssh/sshd_config?

**Comment by ashkulz** [comment]
It looks like `diffie-hellman-group-exchange-sha256` is not supported even in the latest version of libssh (0.7.0), a patch [was proposed in January](http://www.libssh.org/archive/libssh/2015-01/index.html#00012) but did not seem to have been merged yet as it is [pending review](http://www.libssh.org/archive/libssh/2015-01/0000045.html). The only [supported algorithms right now](https://git.libssh.org/projects/libssh.git/tree/include/libssh/crypto.h?h=v0-6#n49) seem to be:
* `diffie-hellman-group1-sha1`
* `diffie-hellman-group14-sha1`
* `ecdh-sha2-nistp256`
* `curve25519-sha256@libssh.org`

**Comment by ashkulz** [comment]
@Mrten: looks like `curve25519-sha256@libssh.org` is the best choice as per the linked article **and** is supported, so that looks like your best bet.

**Comment by Mrten** [comment]
Alas, OpenSSH 5.9 (from ubuntu precise) does not support that algorithm yet :) I'll add `diffie-hellman-group14-sha1` for my coworker, thank you for the link to the libssh docs, but my comment was mainly meant to present an avenue to pursue.

**Comment by jaymore** [comment]
@Mrten : sorry, i do not have read access to /etc/ssh/sshd_config on my server (I dont have a root access).

**Comment by Mrten** [comment]
So I'm now sitting next to someone with NppFTP on a windows laptop, and after enabling `diffie-hellman-group14-sha1` on the ssh server the exchange now fails on the same as above: `[SFTP] Connection failed : kex error : no match for method mac algo client->server: server [hmac-sha2-512,hmac-sha2-256,hmac-ripemd160], client [hmac-sha1] `.So I've enabled the algorithm and everything is peachy.

Have you got a timeframe for libssh 0.7.0?

**Comment by ashkulz** [comment]
@Mrten: I was unable to get it compiling, I use the same setup used for `wkhtmltopdf` for the dependent libs. Will have to try again as it looks like this issue will be solved by the upgrade.

**Comment by ashkulz** [comment]
Please let me know if it works for you with [v0.26.4](https://github.com/ashkulz/NppFTP/releases/tag/v0.26.4).

**Comment by Mrten** [comment]
Remove the just-added `hmac-sha1` from the config and it seems to continue working. Thanks!

**Comment by jordimorillo** [comment]
As an issue for users of notepad++ that are trying to use ftp plugin to connect to the ssh or sftp from a recently updated debian server, just add "hmac-sha1" to the line of /etc/ssh/sshd_config . The issue here is that notepad's++ ftp plugin uses hmac-sha1 to encode the ssh connection but latest ssh updates are working with hmac-sha2 only.

**Comment by nagarjundugyala** [comment]
I am having this issue can anyone help me.. Thanks ! 
kex error : no match for method mac algo client->server: server [hmac-md5,hmac-sha1-96,hmac-md5-96], client [hmac-sha1,hmac-sha2-256,hmac-sha2-512] 

i updated Npp to 0.26.4

**Comment by ashkulz** [comment]
Looks like your server has not been updated as it uses too old and insecure algo support.

**Comment by nagarjundugyala** [comment]
I understand it using hmac-md5-96 Is there a way to connect to that server/ i am not the admin to that server i just need to connect to that and work along, do we have older version of Npp that use same algorithms as server? Thanks for quick reply

**Comment by krishnachaithanyabr** [comment]
Hi All,

I'm getting the below error while use the kex exchange in the SSH2.pm file.

20170706 15:26:01 Command "/apps/tfs/automation/tfs_exec.sh ./get_dli_tfs_files BMO" on host XXXXX failed execution by the Autosys ssh wrapper.
        Return code from the command was 255.

        STDOUT=msg: Create ssh connection object
msg: login to transfer server - ssh
msg: list files from remote server

        STDERR=Use of uninitialized value in concatenation (.) or string at ./get_dli_tfs_files line 121.
2017-07-06 15:26:01 Could not get ls of /Out/bmo
          Exit code=255
          STDOUT=
          STDERR=No kex algorithm at /usr/local/share/perl5/Net/SSH/Perl/SSH2.pm line 92

Below is the SSH2.pm files entry at 92 line.

my $kex = Net::SSH::Perl::Kex->new($ssh);
    $kex->exchange;

can someone please help me with this error.
