### ISSUE TITLE
NppFTP problem on ANdroid Hotspot

### ISSUE THREAD

**Issue by BasMBM** [ashkulz/NppFTP#315]
### Description of the Issue
Recently I’ve been having problems with NppFTP when I work on my Android Hotspot, Notepad++ crashes after opening an FTP connection. It works just fine over the WiFi. Filezilla does work correctly, so there is no blocking of FTP via hotspot.

### Steps to Reproduce the Issue

1. Making a FTP connectie by choosing a connection
2. NppFTP connects, and show the Root folder
3. After showing de root folder crasht Notepad++ 

### Expected Behavior

Showing the fillist

### Actual Behavior

Notepad++ chrashed

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.985
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll 

0.29.7

FTP

Password

**Comment by chcg** [comment]
@BasMBM Do you use a plain FTP connection? Is this reproducible or an once issue. Could you test against the FTP service from https://test.rebex.net/. Or are you familiar with debugging and I could provide you a debug version of nppftp.

**Comment by BasMBM** [comment]
I'll try with Rebex test, when i use FTP with Notepad++ close after connection, while loading file list. When i use FTP/SSL (explicit mode) or FTP/SSL (implicit mode), then the connection stays and i don't have any error :-) Thx, that's my solution!

**Comment by vconcessi** [comment]
I see this issue is closed. I am having this issue connecting via T-Mobile Hotspot. I have no issues connecting Filezilla on the T-mobile "MiFi" unit. Furthermore, I have no issue if I use a Verizon "MiFi" unit.

**Comment by chcg** [comment]
@vconcessi Which version of N++\NppFTP do you use? Any which type of FTP connection (FTP, FTPS, FTPES, SFTP)?

**Comment by vconcessi** [comment]
@chcg I believe I tried both FTP and SFTP. I tried with a VPN as well and still, only the Verizon MiFi unit works, nothing with the T-Mobile MiFi unit.
