### ISSUE TITLE
Please add Fluent UI icon(s) for toolbar

### ISSUE THREAD

**Issue by pryrt** [ashkulz/NppFTP#316]
As of Notepad++ v8.0, plugin authors need to call NPPM_ADDTOOLBARICON_FORDARKMODE instead of NPPM_ADDTOOLBARICON.  (It could be done in an "if", because you can read the NPP version from a plugin; but also, I don't think it hurts to call both messages, so just running both all the time should work as well... though I'm not a plugin developer, so it would be best to confirm that)

### Description of the Issue
Missing toolbar icon when Fluent UI icons selected

### Steps to Reproduce the Issue

1. Notepad++ v8.0
2. Settings > Preferences > General, select one of the Fluent UI icon sets
3. NppFTP icon disappears from toolbar

### Expected Behavior

NppFTP icon should still have icon

### Actual Behavior

NppFTP icon disappears from toolbar

### Debug Information

```
Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\usr\local\apps\notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1256
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll ExtSettings.dll HexEditor.dll LuaScript.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConsole.dll NppConverter.dll NppEditorConfig.dll NppExec.dll NppExport.dll NppFTP.dll NppUISpy.dll PreviewHTML.dll PythonScript.dll QuickText.dll TagLEET.dll XMLTools.dll 

```

**Comment by chcg** [comment]
This was also not working with 7.9.5 and before for the small and big icon set.

**Comment by chcg** [comment]
This was fixed by N++ itself to fallback to existing BMP icon also for dark mode and the fluent icons.
