### ISSUE TITLE
dark mode: icon bug

### ISSUE THREAD

**Issue by gittrolo** [ashkulz/NppFTP#317]
Icon is not shown  in dark mode.

![icon](https://user-images.githubusercontent.com/52664193/123644080-55cfbf80-d825-11eb-9c5c-dcaf14a3222d.JPG)

**Comment by reenlam** [comment]
IMO this is a bug related to Notepad++ itself (so you should report it in their repo), not this plugin. The problem affects not only NppFTP, but also other plugins (at least "Compare" plugin).

**Comment by chcg** [comment]
NppFTP just provides a bmp for the standard icon mode, but no icon for the fluent modes, see https://github.com/ashkulz/NppFTP/blob/2fde112f0af0586dc9ff17285662b13fc14087a1/src/PluginInterface.cpp#L98-L100
