### ISSUE TITLE
What to do, to get committed Pull request back into release stream?

### ISSUE THREAD

**Issue by printpagestopdf** [ashkulz/NppFTP#321]
Hi,

this Pull Request was 
https://github.com/ashkulz/NppFTP/pull/287
was merged into the main branch on 26 Aug 2020 but never released (probably of some regression for #265 ?). Do I have to do anything to get it back into the (next?) release?

Regards

**Comment by chcg** [comment]
@printpagestopdf I thought it would find a way to overcome #265, but this was not the case until now. To get the feature visible the changes need to be backmerged into branch https://github.com/ashkulz/NppFTP/tree/stable_v0_29, which is used for the current releases, also the outdated OpenSSL 1.0.2 is used.

**Comment by printpagestopdf** [comment]
@chcg thank you for the answer. I am not familiar with the procedure here, so I have to ask if that is something I can do or must it be done by somebody with more access rights? Do I have to make a new pull request base on branch https://github.com/ashkulz/NppFTP/tree/stable_v0_29 ?

**Comment by chcg** [comment]
Done via https://github.com/ashkulz/NppFTP/pull/329
