### ISSUE TITLE
Updating Notepad++ Portable removes NppFTP plugin and profiles

### ISSUE THREAD

**Issue by xllentech** [ashkulz/NppFTP#322]
### Description of the Issue
Updating Notepad++ Portable on Portableapps platform removes NppFTP plugin and profiles. Reinstalling the plugin does not restore profiles.

### Steps to Reproduce the Issue

1. If NppFTP plugin instlalled and profiles are populated, Update Notepad++ by default updater of Portableapps.com
2. After update notice, NppFTP plugin no longer installed
3. Reinstall from Plugin Admin, profiles are all gone.

### Expected Behavior
All installed plugins and it's data should be protected during update.

**Comment by chcg** [comment]
The update mechanism of Portable app is not provided from the plugin here. I think you have to check at Portableapps.com, see maybe https://portableapps.com/node/31458 or https://portableapps.com/node/38262.
