### ISSUE TITLE
Notepad++ save button disconnects SFTP connection

### ISSUE THREAD

**Issue by ZebraCow7** [ashkulz/NppFTP#332]
### Description of the Issue
When I click the save button in Notepad++, SFTP connection disconnects. 

### Steps to Reproduce the Issue

1. Initiate SFTP connection
2. NppFTP output: "Connecting"
3. NppFTP output: "[SFTP] Host key accepted."
4. NppFTP output: "[SFTP] Successfully authenticated"
5. NppFTP output: "Connected"
6. Download html file
7. Make changes to file
8. Click save button
9. NppFTP output: "Disconnected"

### Expected Behavior
Changed file is uploaded to server

### Actual Behavior
NppFTP disconnects

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.804
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll 

NppFTP plugin
- zlib version: 1.2.11
- libssh version: 0.9.6
- OpenSSL version: OpenSSL 1.0.2u 20 Dec 2019
- NppFTP version: 0.29.8 Unicode

type of FTP connection: SFTP
type of authentication: password,

**Comment by GeeksRock** [comment]
Having the same issue.

**Comment by ZebraCow7** [comment]
My issue seemed to fix itself randomly. Not sure what changed. 

I used it even with the issue and a few days later it started working right.
