### ISSUE TITLE
SourceForge.net tickets disabled - unable to post bugs and feature requests

### ISSUE THREAD

**Issue by icefront** [ashkulz/NppFTP#344]
Unable to create tickets at https://sourceforge.net/p/nppftp/feature-requests/

Create ticket is greyed out, on hover it says "To create a new ticket, you must be authorized by the project admin".

This is a dead end, the project admin will never know that he needs to authorize somebody.

**Comment by chcg** [comment]
@icefront Sourceforge ticket system is no longer in use. Use github instead.
