### ISSUE TITLE
crash on the list of directories in сyrillic

### ISSUE THREAD

**Issue by ildarkhasanshin** [ashkulz/NppFTP#35]
video: https://yadi.sk/d/J5xyXsOcgyBKS

**Comment by ashkulz** [comment]
Can you post some details?

**Comment by ildarkhasanshin** [comment]
temporary access to the directory /tmp/
user: user47639_tmp
pass: pYiqvT0R
host: 10021987.ru

list of directories /tmp/
https://yadi.sk/i/M79D-3_VgzDAY
