### ISSUE TITLE
Public_html renamed /public_html/public_html

### ISSUE THREAD

**Issue by Bellonio** [ashkulz/NppFTP#351]
### What I have done:
1. Connected to the host
2. Did not double click on folder public_html, but accidentally make the slow double click (so it "ask" me how to rename the folder)
3. Pressed enter (without modify the name) to quickly exit the "renaming folder prompt".

### Expected Behavior
I change nothing so nothing should happen.

### Actual Behavior
It renamed the "/public_html" to "/public_html/public_html". Result ? The folder disappeared (neither in SSH or using another FTP client I see the folder).

#### In the log it print:
`Renamed /public_html to /public_html/public_html`

#### It happened all very quickly, I tried to reproduce the bug but I didn't manage to do it, so I don't know if someone else will have or had already the same problem.

**Comment by chcg** [comment]
Which version of Windows, N++ and NppFTP was used. Did you use SFTP? I can't reproduce it.

**Comment by Bellonio** [comment]
I'm sorry, I did't check the version, and probably now I have a newer version.
I didn't have the same problem from February 20 so I think the bug has been resolved. I close the issue.

Thanks anyway.
