### ISSUE TITLE
Version 0.29.12 Initial remote directory locking as home directory

### ISSUE THREAD

**Issue by j33716** [ashkulz/NppFTP#353]
### Description of the Issue
The new version now locks the "Initial  remote directory" to act as a home directory.
Whatever the Initial remote directory is set to is the base folder. You cannot go below that directory

### Steps to Reproduce the Issue
1. Set Initial remote directory to /var/www/html
2. Open the connection
3. Try to go to /var/spool (or any other folder below the initial)

### Expected Behavior
This was not the case in previous versions. As a developer we work in specific folders 90% of the time but still need access
to the other folders occasionally.  The only way to do this now is to set the initial remote directory to / 
This means to get to the 90% we have to click through folders every time.

The Initial remote directory is now the Home directory

### Debug Information
NppFTP v 0.29.12 Unicode

**Comment by j33716** [comment]
We only use SFTP
We were using 0.29.8 with zlib .11
One system still has this on it

**Comment by chcg** [comment]
@j33716 
A see a changed behaviour which was introduced with 0.29.9. It also happens for plain FTP connections. Before it was possible to trigger a refresh of the directory via double click on the dir entry. Now it is necessary to use either the refresh entry from context menu or the refresh button.
Is this the problem you are facing?

![grafik](https://user-images.githubusercontent.com/12630740/229298807-06af75c0-ce3e-45b1-bfdb-3c13472e7277.png)

**Comment by chcg** [comment]
Duplicates #349
