### ISSUE TITLE
Connection failed : kex error [ssh-rsa,ssh-dss]

### ISSUE THREAD

**Issue by Firehold** [ashkulz/NppFTP#359]
### Description of the Issue
Error when trying to connect to SFTP

### Steps to Reproduce the Issue

1. Try to connect to SFTP with Algo: ssh-rsa,ssh-dss

### Expected Behavior
Normal connection

### Actual Behavior
Error:
[SFTP] Connection failed : kex error : no match for method server host key algo: server [ssh-rsa,ssh-dss], client [ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256] 

### Debug Information
```
Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2134
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    JSMinNPP (1.2205)
    JsonTools (4.4)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppFTP (0.29.12)
    NppTextFX (1.4.1)
```

**Comment by bsy0317** [comment]
I was having the same problem. In my case, I installed the [0.29.9 Releases](https://github.com/ashkulz/NppFTP/releases/tag/v0.29.9) and solved it.

**Comment by chcg** [comment]
Duplicate to https://github.com/ashkulz/NppFTP/issues/348. Please use that issue.
