### ISSUE TITLE
Notepad++ Connection failed : kex error : no match for method server host key algo

### ISSUE THREAD

**Issue by sailorjohn99** [ashkulz/NppFTP#361]
Here is the entire error message:

[SFTP] 

Connection failed : kex error : no match for method server host key algo: 

server [ssh-rsa,ssh-rsa-cert-v01@openssh.com,ssh-dss,ssh-dss-cert-v01@openssh.com], 

client [ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256] 

Unable to connect

Is there a workaround?

**Comment by andreaolivares** [comment]
I've the same problem...

[SFTP] Connection failed : kex error : no match for method server host key algo: server [ssh-rsa,ssh-dss], client [rsa-sha2-512,rsa-sha2-256,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com] 
Unable to connect

**Comment by chcg** [comment]
Duplicate to #359 and #348. As workaround release https://github.com/ashkulz/NppFTP/releases/tag/v0.29.9 could be used but be aware of the security issues which come with it.
