### ISSUE TITLE
NPPftp in notepad++ crahes with sftp connection after latest update

### ISSUE THREAD

**Issue by mflier** [ashkulz/NppFTP#38]
Two days ago de plugin has been updated.
Today i cannot set up a connection by sftp. Though i can set up a connection by ftp.

Below the details of the crash-report.

Probleemhandtekening:
  Gebeurtenisnaam van probleem:	APPCRASH
  Naam van de toepassing:	notepad++.exe
  Versie van toepassing:	6.7.7.0
  Tijdstempel van toepassing:	552ee8f8
  Naam van foutmodule:	NppFTP.dll
  Versie van foutmodule:	0.26.3.0
  Tijdstempel van foutmodule:	036eccf0
  Uitzonderingscode:	c0000005
  Uitzonderingsmarge:	00057271
  Versie van besturingssysteem:	6.3.9600.2.0.0.256.48
  Landinstelling-id:	1043
  Aanvullende informatie 1:	5861
  Aanvullende informatie 2:	5861822e1919d7c014bbb064c64908b2
  Aanvullende informatie 3:	a10f
  Aanvullende informatie 4:	a10ff7d2bb2516fdc753f9c34fc3b069

Please help.

**Comment by ashkulz** [comment]
What is the server you are connecting to? What was the version you were using earlier? Also try using 0.26.4 available from Github.

**Comment by ashkulz** [comment]
@mflier: without any details, I cannot investigate the issue. If you can provide more details, please post them here to reopen it instead of creating a new issue.
