### ISSUE TITLE
Feature request: add cli support

### ISSUE THREAD

**Issue by mrPsycho** [ashkulz/NppFTP#39]
it would be great to support cli. 
why? to use it with mremoteng, for example. 

if it is not possible - so, ok.

**Comment by ashkulz** [comment]
How does CLI support for a Notepad++ plugin make sense? You already have command-line tools to communicate with FTP/SFTP servers.

**Comment by NirBY** [comment]
@mrPsycho is right.
There is FTP/SFTP communicate support, But not a direct Notepad++ FTP/SFTP support.
