### ISSUE TITLE
works only by *try keyboard interactive authentication*

### ISSUE THREAD

**Issue by ildarkhasanshin** [ashkulz/NppFTP#4]
have a server with sftp on valuehost.ru
in filezilla works with a bang
in nppftp only works via a checkbox *try keyboard interactive authentication*
ie need to constantly enter the password
is it possible to fix it?

**Comment by ashkulz** [comment]
It is a problem with the server not allowing password authentication, see this answer on [finding which authentication methods the server supports](http://stackoverflow.com/a/3613342).
