### ISSUE TITLE
crypto not updated

### ISSUE THREAD

**Issue by vonp** [ashkulz/NppFTP#41]
you have updated your plug-in for synwrite, but not for NP++. using the 'hmac-sha1' is the most egregious problem since it was deprecated years ago and all 'sha1' should be dropped EXCEPT for the KEX 'diffie-hellman-group14-sha1' since it has a floor of 2048 bits and will be safe for quite some years. it is well understood that < 1024 bits is "breakable" with current technology and that even 1024 is practical on a sovereign-state level. 

"backdoor" conspiracy theories aside, the EC's foisted upon NIST (i.e., ecdh-sha2-nistp[256|384|521]) used some finite "magic numbers" as	constructors and this -- alone -- makes them inherently suspect.

catering to the following server offerings will modernize your plug-ins towards speed and "best-case"  security and be FIPS 140-2 compliant as well.

Ciphers			aes256-ctr,aes192-ctr
KexAlgorithms	curve25519-sha256@libssh.org,diffie-hellman-group14-sha1
MACs			hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160

it may seem strange to include the hmac-ripemd160's in there since they seem to share the same "N/2" exposure as sha1. however, their methodology is still rock-solid security after a two (2) decade run!

i know that throwing in the addr's is deprecated, but i have found that too many client set-ups do somehow differentiate between "bare" and addressed.

--
thank you,

johann

**Comment by ashkulz** [comment]
Huh? I don't maintain anything for SnyWrite. Also, the 0.26.4 release has updated to libssh `0.7.0` (see #31).

**Comment by vonp** [comment]
well, you should check synwrite out because their sftp module is identical to your NP++ plug-in ... or vice versa.

also, it seems your 0.26.4 has not been released to NP++ since they are still at 0.26.3 for updates.

even using the newer libssh, you are still stuck with 'hmac-sha1,none' for MACs and the synwrite sibling is not. since you are a libssh user, perhaps you would know why they are not using the better security of 'etm' and speedier 'gcm' modes. these have been part of openssh since 6.1. using 'etm' also obviates any hmac worries.

--
thank you,

johann

**Comment by ashkulz** [comment]
Yeah, it is a port of NppFTP to SynWrite mostly maintained by @tbeu. I've not released 0.26.4 as I am thinking to move off SourceForge after the recent shenanigans.

The linked issue shows people able to connect with a stronger MAC i.e. `hmac-sha2-256` with the update. If there is an issue with NppFTP ***not [SynFTP](https://github.com/Alexey-T/SynFTP)***, would appreciate a detailed explanation -- preferably with an example/link to documentation.

**Comment by vonp** [comment]
thank you for your time.

when i looked into libssh 0.7.0 i discovered some anomalies. first, i see that their docs indicate that MACs are still 'MAC hashes: hmac-sha1, none' per their doc's:
http://api.libssh.org/master/

however, their 0.7.0 announcement says they added sha2 MACs, but no details:
https://www.libssh.org/2015/05/11/libssh-0-7-0/

this is confusing since they claimed in '2012-10-12' that "Note we already have support for HMAC_SHA256. HMAC_SHA512 is only needed for the "big" ecdh key exchanges.". an interesting observation, but they had no EC Kex at the time. then that same tracker stated "Add support for hmac-sha2-256 and hmac-sha2-512."
https://red.libssh.org/issues/91

then there is a commit from '2014-04-22' that seems to confirm that they never had 256 and did not add 512 when they said they would, supra:
https://git.libssh.org/projects/libssh.git/commit/?id=4a089026647073be32ddb0885c12f47496bc709b

it is also worthy of note that they -- unlike nearly everyone else -- has retained hmac-md5. now, we both realize that the hash security is fully dependent upon the key; but making modes such as sha1 and md5 available should be well publicized. 

i guess there is no package for you to use the openssh dll's directly and eliminate the dev lag and "second-hand" nature of dealing with libssh.

--
thank you,

johann

**Comment by vonp** [comment]
i am sorry for the lack of courtesy through all this. i would like to specifically thank you for your efforts on behalf of making NP++ even better!

--
johann

**Comment by ashkulz** [comment]
@vonp: it looks like libssh has broken/incomplete documentation. The [supported MAC hashes in 0.7.0](https://git.libssh.org/projects/libssh.git/tree/src/kex.c?h=libssh-0.7.0&id=2721cbc8ee297d39ba5f67ded96bf32699194262#n102) are: `hmac-sha1,hmac-sha2-256,hmac-sha2-512` (as a comparison, 0.6.5 only supports [`hmac-sha1`](https://git.libssh.org/projects/libssh.git/tree/src/kex.c?h=v0-6&id=6e0dee7845cea22f59bd353ef42b31cb67170030#n100)). Disabling `hmac-sha1` would be ideal but not practical as it is sometimes required for connecting to older servers. I think using libssh is better than trying to use the crypto primitives in OpenSSL directly, so that is unlikely to change...

**Comment by vonp** [comment]
yes, 'broken' is a good word for it!

FYI, while they call those modes out in the Kex module, if you look at the wrapper module you will see the actual support level:
https://git.libssh.org/projects/libssh.git/tree/src/wrapper.c?h=libssh-0.7.0&id=2721cbc8ee297d39ba5f67ded96bf32699194262

i am certain you know quite well what will work for you and my thoughts re openssh were mostly prompted by what seems to be libssh's lack of expediency in reacting to the rapid changes so rampant in the security landscape of late. this would affect the treatment of not only "holes", but also innovation. even when "innovation" sometimes takes its cue from a decade ago like in the case of curve25519.

anyway, i am glad your 0.26.4 will be available soon and i hope you send along with it one of those NP++ change notices so people take note when they update.

--
thank you,

johann
