### ISSUE TITLE
Long delay on first connect with FTPS/FTPES

### ISSUE THREAD

**Issue by GwenDragon** [ashkulz/NppFTP#44]
If i connect to a FTPS server, it takes about 30 seconds until a file listing appears.
The problem occurs with local (in LAN, for testing this problem!) Linux proftpd and on FTP servers in WWW.

Using 0.26.3 Unicode with Notepad++ 6.7.9.2 on Windos 7x64.
**//EDIT:** tested same with last 0.26.4 from Git repo here.

NPPTP Log shows:
```
10:43:55 [NppFTP] Everything initialized
10:44:50 -> TYPE I  
10:44:51 Connecting
10:44:51 -> Quit  
10:45:25 220 ProFTPD 1.3.4a Server (Debian) [::ffff:192.168.10.1]
10:45:25 -> AUTH TLS  
10:45:25 234 AUTH TLS successful
10:45:25 [FTPS] Certificate valid.
10:45:25 -> USER test  
10:45:25 331 Password required for test
10:45:25 -> PASS *HIDDEN*
10:45:27 230 User test logged in
10:45:27 -> PBSZ 0  
10:45:27 200 PBSZ 0 successful
10:45:27 -> PROT P  
10:45:27 200 Protection set to Private
10:45:27 -> TYPE A  
10:45:27 200 Type set to A
10:45:27 -> MODE S  
10:45:27 200 Mode set to S
10:45:27 -> STRU F  
10:45:27 200 Structure set to F
10:45:27 -> PWD  
10:45:28 257 "/home/test" is the current directory
10:45:28 Connected
10:45:28 -> CWD /home/test  
10:45:28 250 CWD command successful
10:45:28 -> PASV  
10:45:28 227 Entering Passive Mode (192,168,10,1,219,192).
10:45:28 -> LIST -al   
10:45:28 [FTPS] Certificate valid.
10:45:28 150 Opening ASCII mode data connection for file list
10:45:28 226 Transfer complete
```

Disconnect/Reonnect of same FTPS profile works after this first delay.

Other FTPES clients on same proftpd server show file listing fast, after 2-3 seconds.
openssl 1.0.2c connects very fast (about 1 seond) with `--starttls ftp` to server.
**//EDIT:** and curl connects very fast to the servers over port 21 with ftp-ssl

Known problem?
How can i debug this problem in nppftp?

**Comment by ashkulz** [comment]
Can you try with `0.26.4` (available from the releases page)?

**Comment by GwenDragon** [comment]
I tried it already with the version from https://github.com/ashkulz/NppFTP/releases/tag/v0.26.4

Same problem.

**Comment by ashkulz** [comment]
Not sure why you are getting `Quit` just after connecting. Does that happen on a fresh connection as well?

**Comment by GwenDragon** [comment]
Yes, on fresh connection, too!

**Comment by GwenDragon** [comment]
Any idea to fix or workaround?

**Comment by ashkulz** [comment]
Not really, if you have a public IP where I can test (or how to set up a scenario), I'll try to investigate it.

**Comment by GwenDragon** [comment]
I have send test account to your mail address listed in your Github profile.

**Comment by GwenDragon** [comment]
Did you investigate teh delay at your OS with test account on my server?

After update my PC to Windows 10 Pro x64 the delay of NppFTP disappeared.

**Comment by ashkulz** [comment]
Sorry, I didn't get a chance. Does it happen on any other machines you have access to?

**Comment by GwenDragon** [comment]
On an other machine with Win 7x64 i cant reproduece the issue with Notepad++ 6.8.2 and NppFTP 0.26.5.
FTPES running fine.

So you may close the bug.

**Comment by bipin0108** [comment]
this is the NppFTP - Disconnected.(notepad++)

so i ma trying to connecting but reasons is the profile setting is add and password is don't knows.

so please any one else help me
