### ISSUE TITLE
Lacking of OpenSSH encryption methods

### ISSUE THREAD

**Issue by PeaceDealer** [ashkulz/NppFTP#48]
Hello

We just moved to a new server setup, and since then, I've encountred issues using this plugin.
[SFTP] Connection failed : kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160], client [hmac-sha1] 

Our Backend cordinator told me was a lack of encryption support by the client.

**Comment by ashkulz** [comment]
Use the [0.26.4](https://github.com/ashkulz/NppFTP/releases/tag/v0.26.4) release, which fixes this issue.

**Comment by PeaceDealer** [comment]
May I ask how to install this version? Just tried to run NPP's plugin update feature, but only 0.26.3 is available there.

**Comment by ashkulz** [comment]
Just copy it into your installation directory (you'll need admin privileges)
