### ISSUE TITLE
Wrong encoding in log window (in new version 0.26.1)

### ISSUE THREAD

**Issue by rushan-idrisov** [ashkulz/NppFTP#5]
Wrong encoding in log window in new version 0.26.1 (in prev. version 0.26 it was normal):

200 Ð¢Ð¸Ð¿ ÑÑÑÐ°Ð½Ð¾Ð²Ð»ÐµÐ½ Ð² A
-> MODE S  
200 Ð£ÑÑÐ°Ð½Ð¾Ð²Ð»ÐµÐ½ S ÑÐµÐ¶Ð¸Ð¼
-> STRU F  
200 Ð¡ÑÑÑÐºÑÑÑÐ° ÑÑÑÐ°Ð½Ð¾Ð²Ð»ÐµÐ½Ð° ÐºÐ°Ðº F
-> TYPE I  
200 Ð¢Ð¸Ð¿ ÑÑÑÐ°Ð½Ð¾Ð²Ð»ÐµÐ½ Ð² I
-> SIZE /config.php

**Comment by ashkulz** [comment]
Are you sure it was working in `0.26` or was it some previous release? There are no changes, just an OpenSSL upgrade between `0.26` and `0.26.1`. Also, I don't know what the correct encoding should be or look like, so screenshots would be appreciated.

**Comment by ashkulz** [comment]
Please reopen the issue once you provide more information.
