### ISSUE TITLE
NppFTP Random crash

### ISSUE THREAD

**Issue by mianval** [ashkulz/NppFTP#52]
NPP with NppFTP plugin version 0.26.3 crashes "sometimes" when connecting to an AIX SFTP server.
I think it's related to a large Banner returned by the SFTP server ( greater than 1024 bytes ).
I analyzed a dmp file generated during a crash and i think that could be some kind of buffer overrun.

In source file "StringUtils.cpp" i found this:
line number 315, ret = _vsntprintf(buffer, bufferSize, msgTchar, vaList);
Microsoft "_vsntprintf" function is not the same as the ANSI C version and when the resulting string has the same size than bufferSize a trailing NULL char is not added. 
(https://msdn.microsoft.com/en-us/library/2ts7cx93%28v=vs.110%29.aspx)

May be this is the cause of this particular NPP crash.

**Comment by chcg** [comment]
See https://msdn.microsoft.com/en-US/library/1kt27hek.aspx:

ret = _vsntprintf(buffer, bufferSize, msgTchar, vaList);

Seems it could fail in two ways:
- buffersize might be in bytes and not characters -> all callers need to be check
- as mentioned the trailing NULL -> all callers need to be checked to call buffersize with -1

**Comment by chcg** [comment]
@mianval  Released with https://github.com/ashkulz/NppFTP/releases/tag/v0.27.0, please check
