### ISSUE TITLE
Folder uppercase problem in upload

### ISSUE THREAD

**Issue by ograweb** [ashkulz/NppFTP#56]
Hi

Npp 6.8.1  - French
NppFTP 0.26.3
Server : Linux Debian, vsFTPd 3.0.2
User : Windows 7

Opening file is OK : 
" Download of /laravel/web/app/Models/Role.php succeeded, opening file."

When i save file in specific folder, STOR command fail.

-> TYPE I  
200 Switching to Binary mode.
-> PASV  
227 Entering Passive Mode (37,59,105,64,116,248).
-> STOR /laravel/web/app/models/Role.php  
553 Could not create file.

If i rename foler 'Models' to 'models', Problem is solved.
I think there is a probleme with uppercase in path when NppFTP upload
(Debian is Case sensitive)

**Comment by chcg** [comment]
For files same issue happens, see #3
