### ISSUE TITLE
Notepadd++ Error on startup

### ISSUE THREAD

**Issue by andrewjones216** [ashkulz/NppFTP#57]
Hi 

Since version 6.8.1 > of Notepad++ which comes with NppFTP 0.26.3 notepad++ errors on startup "The program can’t start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."
See the forum post here "https://notepad-plus-plus.org/community/topic/7282/notepad-system-error-on-startup-api-ms-win-crt-runtime-l1-1-0-dll-is-missing"

Believe this may be because NppFTP is using the Visual Studio 2015 Redistributable packages when Notepadd++ comes with the VS2013 Redist packages.

Cheers
Andrew

**Comment by ashkulz** [comment]
I doubt it is a problem with NppFTP, as the released version is compiled with MinGW (I still have to get a MSVC build working) -- it links to `msvcrt.dll` which is present in all OSes since Windows 2000.

**Comment by ashkulz** [comment]
According to `objdump`, it depends on the following DLLs:
```
ADVAPI32.dll
COMCTL32.DLL
COMDLG32.DLL
GDI32.dll
KERNEL32.dll
msvcrt.dll
ole32.dll
SHELL32.dll
SHLWAPI.dll
USER32.dll
WS2_32.dll
```
