### ISSUE TITLE
Timeout gets reset after Notepad++ restart

### ISSUE THREAD

**Issue by dougfultz** [ashkulz/NppFTP#71]
I have changed the timeout for a particular profile to 60 seconds.  After restarting Notepad++, the timeout returns to 0.

`Profile settings > Connection > Timeout (seconds)`

Notepad++ Version: 6.8.3
NppFTP version: 0.26.3 Unicode

**Comment by vlakoff** [comment]
Same issue here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1233

**Comment by chcg** [comment]
Could still be reproduced with v0.27.0

**Comment by chcg** [comment]
release with https://github.com/ashkulz/NppFTP/releases/tag/v0.27.3
