### ISSUE TITLE
ftp panel disappeared

### ISSUE THREAD

**Issue by kirio357** [ashkulz/NppFTP#82]
i cannot find how to show the nppftp panel. after reboot the sidebar is not visible anymore tried:
pluigns/nppftp>show nppftp window but it doesn't show.
Any hints?
if i try to reinstall it will it delete all the usernames/passwords?
thx

**Comment by kirio357** [comment]
solved by reinstalling. profiles ok!

**Comment by chcg** [comment]
@kirio357 Maybe related to #134. Could you confirm it? Did you observe the issue again or could this be closed?

**Comment by kirio357** [comment]
can be closed thx
