### ISSUE TITLE
Npp crashes on connection attempt when NppFTP private keyfile not found

### ISSUE THREAD

**Issue by elevatorguy** [ashkulz/NppFTP#91]
Using a profile with a private key file. If the path to the key file is not found, (file not found) then npp crashes during connection.

to reproduce: 
create SFTP connection using only the keyfile auth method, ask for passphrase is checked.
verify successful connection.
close notepad++
delete or move keyfile.
open notepad++
type in password
-- crash --

**Comment by chcg** [comment]
@elevatorguy Released with https://github.com/ashkulz/NppFTP/releases/tag/v0.27.0, please check
