### ISSUE TITLE
NppFTP 0.26.5 no TLS Handshake no connection

### ISSUE THREAD

**Issue by izanagi23** [ashkulz/NppFTP#93]
Hi guys, excuse my english.
All hoster have worked so far. Now, i have one hoster that connected only with an FTP tool like filezilla but doesnt with Notepad++.
I have taken the same settings as in Filezilla. It must be FTP over TLS (Explicit).
But the NppFTP says

> [NppFTP] Everything initialized
> -> TYPE I
> Connecting
> -> Quit
> 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
> 220-You are user number 1 of 50 allowed.
> 220-Local time is now 00:12. Server port: 21.
> 220-This is a private system - No anonymous login
> 220-IPv6 connections are also welcome on this server.
> 220 You will be disconnected after 15 minutes of inactivity.
> -> AUTH TLS
> 234 AUTH TLS OK.
> Unable to connect
> Disconnected

I tried with active, passiv mode and firewall off. I think it repels the Server-Certification. Have you any idea ?
Regards from germany

**Comment by v4l3r10** [comment]
+1 Same problem after disable TLS1.0 on ftp server.

**Comment by chcg** [comment]
see #122, tls 1.1 and 1.2 not supported yet

**Comment by chcg** [comment]
Considered to be fixed with https://github.com/ashkulz/NppFTP/releases/tag/v0.26.9.
