### ISSUE TITLE
SSH connection problem

### ISSUE THREAD

**Issue by borayeris** [ashkulz/NppFTP#99]
I used to connect my server. I cannot till 2 months. I tested my server with Putty, PHPStorm and FileZilla. All connects by SSH successfully.

Npp version: v6.9.2
NppFTP version: v0.26.3

**Comment by borayeris** [comment]
Up

**Comment by Derkachov** [comment]
Шифрование изменилось, а наш np++ не поддерживает rsa и dss

**Comment by chcg** [comment]
@borayeris Still happening with v0.26.9? Could you provide more infos in case the issue still exists.

N++ debug info. Info from log window.

NppFTP is based on openssh, so the supported ciphers there are the ones you could expect to be supported.

**Comment by borayeris** [comment]
@chcg thank you very much. I was using PHPStorm for sftp. Now I tried NppFTP and tadaa, it's working. What was the bug?

**Comment by chcg** [comment]
Unclear, probably a update of the openssh component.
